Update development.yml
Please 

Signed-off-by: replithater <111firehunter111@gmail.com>

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -20,7 +20,16 @@ jobs:
             platform_name: ios
     
     runs-on: macos-latest
+
     steps:
+      - name: Install required tools
+        run: |
+          brew install ldid gmake cmake wget
+          brew install dpkg fakeroot || true # only if you're building debs
+          which ldid || echo "ldid missing!"
+          ldid -V || echo "ldid version check failed"
+      - name: Force Xcode version
+        run: sudo xcode-select -s /Applications/Xcode_14.3.app
       - name: Install GNU Make (gmake)
         run: brew install make
       - name: Install JDK 8
